name: Merge to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  merge_to_deploy_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        node-version: '16'

    - name: Create and checkout deploy branch
      run: git checkout -b deploy

    - name: Merge changes from main to deploy
      run: git merge main

    - name: Push changes to deploy branch
      uses: ad-m/github-push-action@master
      with:
        branch: deploy
        github_token: ${{ secrets.GITHUB_TOKEN }}
